// @ts-nocheck
// CustomerPilot V6.3 — DEVELOPER MANUAL
// Pure technical reference: API endpoints, DB models, state machines, cron jobs,
// audit actions, and architecture decisions. For developers, not founders.
//
// V6.3: Added Chapter 1 — Queue Engine (Tap to Claim Reward™). This is the
// PRIMARY merchant-customer bridge. Replaces "Search Customer" as default flow.
//
// Each chapter: Topic / Endpoints / DB Models / State Machine / Audit Actions / Notes.

export interface DevChapter {
  id: string
  number: number
  title: string
  tagline: string
  endpoints: { method: string; path: string; purpose: string }[]
  models: string[]
  stateMachine?: { states: string[]; transitions: { from: string; to: string; trigger: string }[] }
  auditActions: string[]
  notes: string[]
}

export const DEVELOPER_MANUAL: DevChapter[] = [
  {
    id: "dev-queue-engine",
    number: 1,
    title: "Queue Engine (Tap to Claim Reward™)",
    tagline: "The PRIMARY merchant-customer bridge. Customer scans QR → WhatsApp → joins queue → merchant taps → reward. Replaces 'Search Customer' as default flow. CustomerPilot starts AFTER payment.",
    endpoints: [
      { method: "POST", path: "/api/queue/join", purpose: "Customer scans QR → joins merchant's queue. Creates customer if new (no forms). Returns queueId + position + expiresAt." },
      { method: "GET", path: "/api/queue", purpose: "Merchant fetches waiting customers (live queue). Sorted newest first. Auto-expires after 5 min." },
      { method: "POST", path: "/api/queue/claim", purpose: "Merchant taps customer → enters amount (optional) → confirms. Awards stamps, sends WhatsApp, removes from queue." },
    ],
    models: ["WaitingCustomer", "Customer", "Bill", "Stamp", "WhatsAppMessage", "AuditLog"],
    stateMachine: {
      states: ["scanned", "waiting", "claimed", "expired", "cancelled"],
      transitions: [
        { from: "(none)", to: "scanned", trigger: "Customer scans QR (POST /api/queue/join)" },
        { from: "scanned", to: "waiting", trigger: "WaitingCustomer row created with status='waiting', expiresAt = now + 5min" },
        { from: "waiting", to: "claimed", trigger: "Merchant taps (POST /api/queue/claim) → stamps awarded, WhatsApp sent" },
        { from: "waiting", to: "expired", trigger: "Cron: expiresAt < now → status='expired'" },
        { from: "waiting", to: "cancelled", trigger: "Customer cancels (future: WhatsApp 'CANCEL' reply)" },
      ],
    },
    auditActions: ["QUEUE_JOINED", "QUEUE_CLAIMED", "QUEUE_EXPIRED", "QUEUE_CANCELLED", "QUEUE_DUPLICATE_SCAN_IGNORED"],
    notes: [
      "CORE PHILOSOPHY: CustomerPilot starts AFTER payment. It works with cash, UPI, existing POS, card, or no bill. Never asks for bill number, GST, invoice, tax, or HSN.",
      "joinQueue() is idempotent on (customerId, status='waiting'). If customer scans again while already waiting, returns existing entry (duplicate scan ignored).",
      "New customers are created instantly with minimal data: name (or 'Customer XXXX' fallback), phone, referralCode auto-generated. No forms, no password, no app download.",
      "claimFromQueue() creates a Bill internally (for audit trail + stamp engine) but the bill is NOT shown to customer as an invoice. It's a 'purchase event' record.",
      "Amount is OPTIONAL. If merchant doesn't enter amount (no-bill merchant), bill.amount=0, but stamps are still awarded (default 1 stamp via stamp engine).",
      "Queue timeout: 5 minutes (QUEUE_TIMEOUT_MINUTES in queue-engine.ts). Configurable per merchant in future.",
      "V6.2 fraud check: if cashier.requireManagerApprovalUntil is set, claimFromQueue() returns 403. Prevents flagged cashiers from claiming.",
      "VIP bonus multiplier applied in awardStampsForBill() (called internally by claimFromQueue). Gold=1.2x, Platinum=1.5x.",
      "Auto-refresh: frontend polls GET /api/queue every 5 seconds. Could upgrade to WebSocket in production for true real-time.",
      "Live Queue is the DEFAULT view (view='queue' in page.tsx). Old POS 'Search Customer' flow demoted to 'Manual Search (Exception)'.",
    ],
  },
  {
    id: "dev-onboarding",
    number: 2,
    title: "Onboarding Engine (2-Minute Path)",
    tagline: "How the fast-start onboarding flow works. Default card auto-created; merchant bills immediately.",
    endpoints: [
      { method: "POST", path: "/api/merchants/signup", purpose: "Create merchant + owner staff + trial subscription" },
      { method: "POST", path: "/api/onboarding", purpose: "Mark an OnboardingStep as completed/skipped" },
      { method: "GET", path: "/api/state", purpose: "Returns onboardingSteps[] for the dashboard widget" },
    ],
    models: ["Merchant", "Staff", "Subscription", "StampCard", "OnboardingStep"],
    stateMachine: {
      states: ["signup", "default_card", "qr_ready", "first_bill", "add_staff", "import_customers", "add_rewards", "configure_birthday"],
      transitions: [
        { from: "(none)", to: "signup", trigger: "merchant.created" },
        { from: "signup", to: "default_card", trigger: "fastStartOnboarding() creates a StampCard from DEFAULT_CARD_BY_BUSINESS[businessType]" },
        { from: "default_card", to: "qr_ready", trigger: "auto — POS opens" },
        { from: "qr_ready", to: "first_bill", trigger: "first POST /api/bills" },
        { from: "(any)", to: "add_staff|import_customers|add_rewards|configure_birthday", trigger: "merchant completes optional step" },
      ],
    },
    auditActions: ["MERCHANT_CREATED", "ONBOARDING_STEP_DONE"],
    notes: [
      "fastStartOnboarding() is idempotent — safe to call on every login. It only seeds missing rows.",
      "OnboardingStep.skipped is a separate flag from completed. Skipped steps don't count against the progress percentage but are tracked for analytics.",
      "Merchant.onboardingCompleted is set to true when all required steps (signup, default_card, qr_ready) are done. Optional steps don't block this flag.",
      "DEFAULT_CARD_BY_BUSINESS lives in src/lib/onboarding-engine.ts. Add new business types there.",
    ],
  },
  {
    id: "dev-rbac",
    number: 3,
    title: "RBAC (Role-Based Access Control)",
    tagline: "Owner / Manager / Cashier permission matrix. Enforced server-side on every POST.",
    endpoints: [
      { method: "POST", path: "/api/rbac/check", purpose: "Pure permission check, no side effects" },
      { method: "POST", path: "/api/staff", purpose: "Create staff (owner only)" },
    ],
    models: ["Staff"],
    auditActions: ["RBAC_DENIED", "STAFF_CREATED", "STAFF_SUSPENDED"],
    notes: [
      "can(role, permission) is the only check — call it at the top of every POST handler before any DB write.",
      "On denial, ALWAYS create an AuditLog with action=RBAC_DENIED. This is the insider-threat signal.",
      "ROLE_PERMISSIONS in src/lib/rbac.ts is the single source of truth. Frontend hides UI based on can(), but server enforcement is mandatory.",
      "PIN is a 4-digit string. In production, hash with bcrypt. For demo, stored as plaintext.",
      "Cashier cannot: void/refund bills, approve referrals, create/edit rewards, manage staff, view audit log.",
      "Manager cannot: create/suspend staff, view subscription, change merchant settings.",
      "Owner: full access.",
    ],
  },
  {
    id: "dev-stamp-engine",
    number: 4,
    title: "Stamp Engine",
    tagline: "How stamps are awarded, spent, and reversed. VIP multiplier applied at award time.",
    endpoints: [
      { method: "POST", path: "/api/bills", purpose: "Create bill → awardStampsForBill() called internally" },
      { method: "POST", path: "/api/bills/void", purpose: "Reverse stamps tied to that bill" },
      { method: "POST", path: "/api/bills/refund", purpose: "Same as void but keeps bill in ledger as 'refunded'" },
      { method: "POST", path: "/api/rewards/redeem", purpose: "spendStampsForRedemption() consumes completed cards" },
    ],
    models: ["Stamp", "CustomerStampCard", "Bill", "Redemption", "Customer"],
    stateMachine: {
      states: ["empty", "in_progress", "completed", "redeemed"],
      transitions: [
        { from: "(none)", to: "empty", trigger: "CustomerStampCard.create() on first stamp award" },
        { from: "empty", to: "in_progress", trigger: "first Stamp row linked to it" },
        { from: "in_progress", to: "completed", trigger: "stampsCollected >= stampsRequired" },
        { from: "completed", to: "redeemed", trigger: "spendStampsForRedemption() on successful redemption" },
        { from: "completed", to: "in_progress", trigger: "bill refund/void reverses stamps; completed flag cleared" },
      ],
    },
    auditActions: ["BILL_CREATED", "BILL_VOIDED", "BILL_REFUNDED", "REDEMPTION_APPROVED"],
    notes: [
      "stampsForAmount(rule, amount) parses rule strings: '1' = flat 1 stamp, '1 per $N' = floor(amount/N) capped at 5.",
      "VIP bonus is applied AFTER stampsForAmount: actualStamps = floor(baseStamps × tier.bonusMultiplier).",
      "On bill void/refund, ALL Stamp rows tied to that billId are deleted. CustomerStampCard.stampsCollected is decremented by that count, completed flag cleared if it drops below threshold.",
      "Edge case: if a redemption already happened on a completed card, refunding the bill that completed it leaves an 'unearned' redemption. Audit log captures this; manual reconciliation required.",
      "Customer.lifetimeStamps and lifetimeSpend are incremented on bill creation, decremented on void/refund. These should always equal sum(Stamp) and sum(Bill.amount where status=confirmed).",
    ],
  },
  {
    id: "dev-vip-engine",
    number: 5,
    title: "VIP Tier Engine",
    tagline: "Auto-upgrade customers based on lifetimeSpend. Multiplier applied at stamp award time.",
    endpoints: [
      { method: "GET", path: "/api/state", purpose: "Returns vipTiers[] for display" },
    ],
    models: ["VipTier", "Customer.vipTier"],
    stateMachine: {
      states: ["none", "silver", "gold", "platinum"],
      transitions: [
        { from: "none", to: "silver", trigger: "Customer.lifetimeSpend >= 2000" },
        { from: "silver", to: "gold", trigger: "Customer.lifetimeSpend >= 5000" },
        { from: "gold", to: "platinum", trigger: "Customer.lifetimeSpend >= 10000" },
      ],
    },
    auditActions: ["VIP_TIER_UPGRADED"],
    notes: [
      "Tiers are one-way — customers never downgrade even if their spend stalls.",
      "DEFAULT_VIP_TIERS in src/lib/vip-engine.ts is the reference. Merchants can override thresholds via VipTier rows in DB.",
      "applyVipBonusStamps(base, tier) = floor(base × multiplier). Floor — never inflate via rounding.",
      "On tier upgrade, an Achievement row is auto-created (vip_silver / vip_gold / vip_platinum) + WhatsApp queued.",
      "Tier check happens in awardStampsForBill() AFTER stampsForAmount() but BEFORE writing Stamp rows.",
    ],
  },
  {
    id: "dev-review-engine",
    number: 6,
    title: "Google Review Engine",
    tagline: "AI-drafted reviews post-redemption, bonus stamps on submit, reputation score calculation.",
    endpoints: [
      { method: "GET", path: "/api/reviews", purpose: "List all reviews" },
      { method: "POST", path: "/api/reviews/draft", purpose: "Generate AI draft + queue WhatsApp to customer" },
      { method: "POST", path: "/api/reviews/submit", purpose: "Customer submits review → bonus stamps awarded" },
    ],
    models: ["Review"],
    stateMachine: {
      states: ["requested", "draft_ready", "submitted", "declined", "expired"],
      transitions: [
        { from: "(none)", to: "requested", trigger: "Redemption completed → auto-request OR manual trigger" },
        { from: "requested", to: "draft_ready", trigger: "POST /api/reviews/draft generates AI draft" },
        { from: "draft_ready", to: "submitted", trigger: "Customer edits/submits via WhatsApp reply or POS" },
        { from: "requested|draft_ready", to: "declined", trigger: "Customer says no OR 14 days pass with no action" },
        { from: "declined", to: "expired", trigger: "30 days total elapsed" },
      ],
    },
    auditActions: ["REVIEW_DRAFT_GENERATED", "REVIEW_SUBMITTED", "REVIEW_DECLINED"],
    notes: [
      "Bonus formula in src/lib/review-engine.ts: base 1 stamp + 1 if 5-star + 2 if photo. Max 4 stamps per review.",
      "generateReviewDraft() is a template-based generator in this demo. In production, swap for an LLM call (z-ai-web-dev-sdk chat completion).",
      "computeReputationScore() walks all submitted reviews and produces a 0-100 score. Used by the dashboard reputation widget.",
      "Photo URL is mocked as 'https://example.com/photo.jpg' in the demo. Production should accept an upload from the WhatsApp message.",
      "Review.requestSource values: 'post_redemption' (best, customer is happy), 'post_bill', 'manual' (manager-triggered), 'birthday'.",
    ],
  },
  {
    id: "dev-birthday-engine",
    number: 7,
    title: "Birthday Engine",
    tagline: "7-day reminder + 7-day redemption window. Bonus stamps during window only.",
    endpoints: [
      { method: "POST", path: "/api/birthdays", purpose: "Set/update customer birthday + schedule" },
      { method: "POST", path: "/api/birthdays/redeem", purpose: "Redeem birthday reward (within window)" },
    ],
    models: ["Birthday", "Customer.birthday"],
    stateMachine: {
      states: ["scheduled", "reminder_sent", "reward_ready", "redeemed", "missed"],
      transitions: [
        { from: "(none)", to: "scheduled", trigger: "POST /api/birthdays creates Birthday row" },
        { from: "scheduled", to: "reminder_sent", trigger: "Cron: 7 days before birthday, send WhatsApp reminder" },
        { from: "reminder_sent", to: "reward_ready", trigger: "Cron: birthday day arrives, window opens" },
        { from: "reward_ready", to: "redeemed", trigger: "POST /api/birthdays/redeem during window" },
        { from: "reward_ready", to: "missed", trigger: "Cron: 7 days after birthday, window closed, no redemption" },
      ],
    },
    auditActions: ["BIRTHDAY_SET", "BIRTHDAY_REDEEMED", "BIRTHDAY_MISSED"],
    notes: [
      "Customer.birthday stored as 'MM-DD' string (no year, privacy).",
      "Birthday.customerId is @unique — one birthday per customer.",
      "computeBirthdaySchedule() returns next occurrence. If birthday has passed this year, returns next year's date.",
      "Redemption window is hard-enforced: POST /api/birthdays/redeem returns 409 if outside windowStart..windowEnd.",
      "Birthday bonus stamps use source='birthday_bonus' on the Stamp row, so reports can break down by source.",
      "VIP tiers can grant higher birthday bonus: Platinum gets 5 stamps + free cake vs Gold's 3 stamps + free slice.",
    ],
  },
  {
    id: "dev-winback-engine",
    number: 8,
    title: "Win-back Escalation Engine",
    tagline: "30/45/60/90 day escalation. Each stage has an owner + channel + message template.",
    endpoints: [
      { method: "POST", path: "/api/winback", purpose: "Manually advance a customer to the next win-back stage" },
    ],
    models: ["WinBackEscalation"],
    stateMachine: {
      states: ["day_30", "day_45", "day_60", "day_90", "recovered", "lost"],
      transitions: [
        { from: "(none)", to: "day_30", trigger: "Cron: Customer.lastActiveAt is 30+ days ago" },
        { from: "day_30", to: "day_45", trigger: "Cron: 15 days pass, customer still inactive" },
        { from: "day_45", to: "day_60", trigger: "Cron: 15 more days pass" },
        { from: "day_60", to: "day_90", trigger: "Cron: 30 more days pass" },
        { from: "day_90", to: "lost", trigger: "Cron: 30 more days pass (120 total)" },
        { from: "(any)", to: "recovered", trigger: "Customer creates a bill (lastActiveAt updates)" },
      ],
    },
    auditActions: ["WINBACK_ESCALATED", "WINBACK_RECOVERED", "WINBACK_LOST"],
    notes: [
      "WIN_BACK_STAGES in src/lib/winback-engine.ts is the source of truth for stage configs.",
      "Each stage has an owner: system (auto), manager (task in their queue), owner (urgent task).",
      "Channel determines delivery: whatsapp (auto-sent), phone_call (manager/owner task to call manually).",
      "On customer recovery (bill created), all open WinBackEscalation rows are marked outcome='recovered'. Customer.status returns to 'active' if it was 'dormant'.",
      "At 120 days inactive, customer.status flips to 'churned'. Removed from active win-back queue but kept in DB for re-engagement campaigns.",
      "POST /api/winback allows manual escalation (e.g. owner wants to skip ahead for a high-value churn risk).",
    ],
  },
  {
    id: "dev-billing",
    number: 9,
    title: "Billing Workflow (POS)",
    tagline: "Bill creation → stamp award → WhatsApp queue. Duplicate-prevention on rapid double-click.",
    endpoints: [
      { method: "POST", path: "/api/bills", purpose: "Create confirmed bill" },
      { method: "POST", path: "/api/bills/void", purpose: "Void (clerical error) — manager+" },
      { method: "POST", path: "/api/bills/refund", purpose: "Refund (money back) — manager+" },
    ],
    models: ["Bill", "Stamp", "CustomerStampCard", "Customer", "WhatsAppMessage", "AuditLog"],
    stateMachine: {
      states: ["draft", "confirmed", "voided", "refunded"],
      transitions: [
        { from: "(none)", to: "confirmed", trigger: "POST /api/bills (we don't persist draft state)" },
        { from: "confirmed", to: "voided", trigger: "POST /api/bills/void (clerical error)" },
        { from: "confirmed", to: "refunded", trigger: "POST /api/bills/refund (customer return)" },
      ],
    },
    auditActions: ["BILL_CREATED", "BILL_VOIDED", "BILL_REFUNDED"],
    notes: [
      "Bill number format: CP-YYYY-NNNN (or SC- for Sweet Crumb). Auto-generated from merchant prefix + year + zero-padded count.",
      "Duplicate prevention: backend should reject a second POST /api/bills with same customerId+amount within 5 seconds. (TODO in production — currently relies on frontend button-disable.)",
      "On bill creation: 1) Bill row created, 2) awardStampsForBill() called, 3) Customer stats incremented, 4) WhatsApp queued (stamp_earned OR reward_ready if card completed), 5) AuditLog written.",
      "On void/refund: stamps deleted, CustomerStampCard.stampsCollected decremented, completed flag cleared, Customer stats decremented. Bill row kept in ledger with new status.",
      "Bill.notes is overloaded: void/refund stores 'VOIDED: <reason>' or 'REFUND: <reason>' for audit clarity.",
    ],
  },
  {
    id: "dev-customer-import",
    number: 10,
    title: "Customer Import Pipeline",
    tagline: "Multi-source import: CSV, manual, phone contacts. Duplicate prevention by phone.",
    endpoints: [
      { method: "POST", path: "/api/customers", purpose: "Single customer creation" },
      { method: "POST", path: "/api/customers/import", purpose: "Bulk CSV import with WhatsApp invite queue" },
      { method: "POST", path: "/api/customers/favorite", purpose: "Toggle favorite flag" },
      { method: "POST", path: "/api/customers/notes", purpose: "Update merchant notes" },
      { method: "POST", path: "/api/customers/block", purpose: "Block/unblock customer (manager+)" },
    ],
    models: ["Customer"],
    auditActions: ["CUSTOMER_CREATED", "CUSTOMERS_IMPORTED", "CUSTOMER_BLOCKED", "CUSTOMER_UNBLOCKED", "CUSTOMER_DUPLICATE_BLOCKED"],
    notes: [
      "Duplicate check: db.customer.findFirst({ where: { merchantId, phone } }). Returns 409 with existing customer's name.",
      "referralCode is auto-generated on creation: prefix + 8 random alphanumeric chars. @unique constraint.",
      "referredById is resolved from referredByCode at creation time. If code doesn't match, the field is silently null (no error).",
      "Import returns per-row results: [{ row, status: 'imported' | 'duplicate' | 'invalid', customerId? }].",
      "acquisitionChan is auto-set based on context: 'import' for bulk, 'referral' if referredByCode resolves, 'walk_in' otherwise.",
      "Customer.favorite is a merchant-set flag for fast POS access. Customer.notes is free-text merchant notes (e.g. 'allergic to nuts').",
    ],
  },
  {
    id: "dev-redemptions",
    number: 11,
    title: "Redemption Workflow",
    tagline: "Stock check → manager approval branch → stamp spend → WhatsApp confirm.",
    endpoints: [
      { method: "POST", path: "/api/rewards/redeem", purpose: "Redeem a reward for a customer" },
      { method: "POST", path: "/api/rewards", purpose: "Create new reward (manager+)" },
    ],
    models: ["Redemption", "Reward", "CustomerStampCard"],
    stateMachine: {
      states: ["pending_approval", "completed", "denied", "reversed"],
      transitions: [
        { from: "(none)", to: "pending_approval", trigger: "Cashier tries to redeem a requiresManagerApproval=true reward" },
        { from: "(none)", to: "completed", trigger: "Manager/owner redeems OR cashier redeems non-approval reward" },
        { from: "pending_approval", to: "completed", trigger: "Manager approves" },
        { from: "pending_approval", to: "denied", trigger: "Manager denies" },
        { from: "completed", to: "reversed", trigger: "Manager reverses (e.g. customer returned the reward)" },
      ],
    },
    auditActions: ["REDEMPTION_PENDING_APPROVAL", "REDEMPTION_APPROVED", "REDEMPTION_DENIED", "REDEMPTION_OUT_OF_STOCK", "REDEMPTION_REVERSED"],
    notes: [
      "Stock check happens BEFORE stamp spend. If stock <= 0, return 409, no stamps consumed, AuditLog REDEMPTION_OUT_OF_STOCK.",
      "spendStampsForRedemption({ customerId, rewardCost }) finds the N oldest completed+unredeemed CustomerStampCards and marks them redeemed. If fewer than N available, returns failure with reason.",
      "Manager approval branch: when staff.role=CASHIER && reward.requiresManagerApproval=true, create Redemption with status='pending_approval'. NO stamps consumed yet. Manager approves via (TODO) POST /api/redemptions/approve.",
      "Reward.stock is decremented atomically. In production, wrap in a transaction with the CustomerStampCard update.",
      "Reward.stampsCost is in 'completed card' units, not raw stamps. A 9-stamp card = 1 unit. Cost of 3 = 3 completed cards = 27 raw stamps.",
    ],
  },
  {
    id: "dev-referrals",
    number: 12,
    title: "Referral Pipeline",
    tagline: "Share → friend joins → first purchase verifies → manager approves → bonus stamps.",
    endpoints: [
      { method: "POST", path: "/api/referrals", purpose: "Create referral (referrer + friend phone)" },
      { method: "POST", path: "/api/referrals/approve", purpose: "Approve verified referral → bonus stamps to both" },
      { method: "POST", path: "/api/referrals/flag", purpose: "Flag as suspected fraud (manager+)" },
    ],
    models: ["Referral"],
    stateMachine: {
      states: ["pending", "joined", "verified", "approved", "denied", "fraud_flagged"],
      transitions: [
        { from: "(none)", to: "pending", trigger: "POST /api/referrals" },
        { from: "pending", to: "joined", trigger: "Friend registers with referralCode (POST /api/customers with referredByCode)" },
        { from: "joined", to: "verified", trigger: "Friend's first bill created (POST /api/bills)" },
        { from: "verified", to: "approved", trigger: "Manager clicks Approve → POST /api/referrals/approve" },
        { from: "verified", to: "denied", trigger: "Manager clicks Deny (TODO)" },
        { from: "(any)", to: "fraud_flagged", trigger: "POST /api/referrals/flag" },
      ],
    },
    auditActions: ["REFERRAL_CREATED", "REFERRAL_APPROVED", "REFERRAL_FLAGGED_FRAUD"],
    notes: [
      "Referral uniqueness: db.referral.findFirst({ where: { merchantId, referrerId, friendPhone } }). Returns 409 if duplicate.",
      "Approval awards 1 bonus stamp to referrer AND 1 to friend. Both get Stamp rows with source='referral_bonus'.",
      "Bonus is applied to the customer's active CustomerStampCard (creating one if needed).",
      "Fraud flag is terminal — a flagged referral can never be approved. Used for suspicious patterns (same phone referred by multiple accounts).",
      "referralCode is on the Customer model, not Referral. The referrer shares their code; the friend uses it during registration.",
    ],
  },
  {
    id: "dev-whatsapp",
    number: 13,
    title: "WhatsApp Message Queue",
    tagline: "Simulated provider with queued/sent/delivered/failed/delayed states. Background flush.",
    endpoints: [
      { method: "GET", path: "/api/state", purpose: "Returns waMessages[] for the WhatsApp view" },
    ],
    models: ["WhatsAppMessage"],
    stateMachine: {
      states: ["queued", "sent", "delivered", "failed", "delayed"],
      transitions: [
        { from: "(none)", to: "queued", trigger: "Any action that creates a WhatsAppMessage" },
        { from: "queued", to: "sent", trigger: "Background worker picks it up" },
        { from: "sent", to: "delivered", trigger: "Provider webhook (simulated)" },
        { from: "queued|sent", to: "delayed", trigger: "3 failed retry attempts" },
        { from: "delayed", to: "delivered", trigger: "Provider recovers, queue flushes" },
        { from: "delayed", to: "failed", trigger: "24 hours elapsed with no delivery" },
      ],
    },
    auditActions: ["WHATSAPP_QUEUED", "WHATSAPP_FAILED"],
    notes: [
      "Templates: invite, stamp_earned, reward_ready, redemption_confirm, referral_bonus, referral_invite, churn_reminder_30, churn_offer_45, churn_manager_call_60, churn_owner_call_90, birthday_reminder, birthday_redeemed, review_request, review_thank_you, churn_winback.",
      "Demo mode: messages stay in 'queued' state forever. In production, a background worker (cron or queue) flushes them.",
      "Customer.whatsappOptIn=false suppresses all non-essential messages. Transactional messages (redemption confirmations) still sent.",
      "Photo URL on Review is a placeholder in the demo. Production should accept image uploads via WhatsApp media API.",
      "Provider outage simulation: queue status='delayed' after 3 retries. Merchant sees a 'WhatsApp queue delayed' alert on dashboard.",
    ],
  },
  {
    id: "dev-audit-log",
    number: 14,
    title: "Audit Log Architecture",
    tagline: "Append-only event log. Every monetary/permission event traceable to actor.",
    endpoints: [
      { method: "GET", path: "/api/state", purpose: "Returns auditLogs[] (last 200)" },
    ],
    models: ["AuditLog"],
    auditActions: [
      "MERCHANT_CREATED", "STAFF_CREATED", "STAFF_SUSPENDED",
      "CUSTOMER_CREATED", "CUSTOMERS_IMPORTED", "CUSTOMER_BLOCKED", "CUSTOMER_UNBLOCKED", "CUSTOMER_DUPLICATE_BLOCKED",
      "CARD_CREATED", "CARD_EDITED",
      "BILL_CREATED", "BILL_VOIDED", "BILL_REFUNDED",
      "REDEMPTION_PENDING_APPROVAL", "REDEMPTION_APPROVED", "REDEMPTION_DENIED", "REDEMPTION_REVERSED", "REDEMPTION_OUT_OF_STOCK",
      "REFERRAL_CREATED", "REFERRAL_APPROVED", "REFERRAL_FLAGGED_FRAUD",
      "REVIEW_DRAFT_GENERATED", "REVIEW_SUBMITTED", "REVIEW_DECLINED",
      "BIRTHDAY_SET", "BIRTHDAY_REDEEMED", "BIRTHDAY_MISSED",
      "VIP_TIER_UPGRADED",
      "WINBACK_ESCALATED", "WINBACK_RECOVERED", "WINBACK_LOST",
      "RBAC_DENIED",
      "SUPPORT_TICKET_CREATED", "SUPPORT_TICKET_RESOLVED",
      "ONBOARDING_STEP_DONE",
      "SUBSCRIPTION_ACTIVATED", "SUBSCRIPTION_RENEWED", "SUBSCRIPTION_PAYMENT_FAILED",
    ],
    notes: [
      "AuditLog is append-only — never UPDATE or DELETE a row. Corrections are new rows with reference to the original.",
      "actorType: STAFF | SYSTEM | CUSTOMER. actorId + staffId are populated when actorType=STAFF.",
      "metadata is a JSON string. Parse on read for display: JSON.parse(log.metadata).",
      "entity + entityId let you filter by topic (e.g. all events for a specific Bill).",
      "RBAC_DENIED entries are the insider-threat signal. Owner should review these weekly.",
      "In production, partition AuditLog by month for query performance. SQLite doesn't support this; Postgres does.",
    ],
  },
  {
    id: "dev-subscription",
    number: 15,
    title: "Subscription & Payment Gating",
    tagline: "Trial → active → payment_failed → grace → suspended. Write APIs gated by Merchant.status.",
    endpoints: [
      { method: "POST", path: "/api/seed", purpose: "Reseed demo data (dev only)" },
    ],
    models: ["Subscription", "Merchant.status", "Merchant.trialEndsAt"],
    stateMachine: {
      states: ["trial", "active", "payment_failed", "grace", "suspended", "cancelled"],
      transitions: [
        { from: "(none)", to: "trial", trigger: "Merchant signup (14-day trial)" },
        { from: "trial", to: "active", trigger: "Owner pays subscription OR trial auto-converts at no cost (demo)" },
        { from: "active", to: "payment_failed", trigger: "Renewal charge fails" },
        { from: "payment_failed", to: "grace", trigger: "24 hours pass with no payment update" },
        { from: "grace", to: "suspended", trigger: "7 days pass with no payment update" },
        { from: "suspended", to: "active", trigger: "Owner updates payment + pays" },
        { from: "(any)", to: "cancelled", trigger: "Owner cancels subscription" },
      ],
    },
    auditActions: ["SUBSCRIPTION_ACTIVATED", "SUBSCRIPTION_RENEWED", "SUBSCRIPTION_PAYMENT_FAILED", "SUBSCRIPTION_SUSPENDED", "SUBSCRIPTION_REACTIVATED"],
    notes: [
      "Trial: 14 days. All features unlocked. No credit card required. Merchant.trialEndsAt set on signup.",
      "Cron runs daily: if trial ended and no subscription → mark Merchant.status='suspended' (after 7-day grace).",
      "Suspended state: all POST APIs return 402 Payment Required. GET /api/state still works (read-only). Data never deleted.",
      "Recovery: owner updates payment method → Subscription.status='active', Merchant.status='active'. All features restored. No data loss.",
      "In production, integrate with Razorpay/Stripe webhooks for auto-renewal. Webhook → update Subscription.renewalDate.",
      "Subscription.amount is in paise (Indian convention) or rupees — be consistent. Demo uses rupees.",
    ],
  },
  {
    id: "dev-cron-jobs",
    number: 16,
    title: "Cron Jobs (Background Workers)",
    tagline: "Daily/weekly scheduled jobs. In demo, simulated via API triggers; in production, use Vercel Cron or a queue.",
    models: [], endpoints: [], auditActions: [],
    notes: [
      "DAILY 9:00 AM — Birthday reminder sweep:",
      "  For each Birthday where today == rewardWindowStart:",
      "    → Send WhatsApp (template: birthday_reminder)",
      "    → Update Birthday.status='reminder_sent', reminderSentAt=now",
      "  For each Birthday where today > rewardWindowEnd AND status != 'redeemed':",
      "    → Update Birthday.status='missed'",
      "    → Send 'belated' WhatsApp if not already sent",
      "",
      "DAILY 9:00 AM — Win-back escalation sweep:",
      "  For each Customer:",
      "    → Compute daysSinceLastActive",
      "    → If 30/45/60/90 day threshold crossed AND no existing escalation at that stage:",
      "      → Create WinBackEscalation row",
      "      → Send WhatsApp (or create manager/owner task for phone_call stages)",
      "    → If 120 days AND status != 'churned':",
      "      → Update Customer.status='churned'",
      "      → Mark latest escalation outcome='lost'",
      "",
      "DAILY 10:00 AM — WhatsApp queue flush:",
      "  For each WhatsAppMessage where status='queued':",
      "    → Send via provider",
      "    → Update status='sent' on success, retry on failure (max 3)",
      "    → If 3 failures: status='delayed'",
      "  For each WhatsAppMessage where status='delayed' AND age > 24h:",
      "    → status='failed', alert merchant",
      "",
      "DAILY 6:00 PM — Daily summary WhatsApp to merchant:",
      "  Compose: today's bills count, revenue, new customers, top customer, pending approvals",
      "  Send to merchant.whatsappPhone",
      "",
      "WEEKLY Monday 9 AM — Churn risk recompute:",
      "  For each Customer: recompute churnRiskScore = computeChurnRisk({...})",
      "  Update Customer.churnRiskScore field",
      "",
      "DAILY — Subscription check:",
      "  For each Subscription where status='active' AND renewalDate < now:",
      "    → Attempt auto-renewal (Razorpay charge)",
      "    → On success: renewalDate += plan duration, AuditLog SUBSCRIPTION_RENEWED",
      "    → On failure: status='payment_failed', send urgent WhatsApp + email to owner",
      "  For each Merchant where status='trial' AND trialEndsAt < now:",
      "    → status='suspended' (after 7-day grace)",
      "",
      "HOURLY — Review expiry sweep:",
      "  For each Review where status='requested' AND createdAt < now - 14 days:",
      "    → status='declined'",
      "  For each Review where status='declined' AND createdAt < now - 30 days:",
      "    → status='expired'",
    ],
  },
  {
    id: "dev-state-snapshot",
    number: 17,
    title: "State Snapshot API (Single Source of Truth)",
    tagline: "GET /api/state returns the entire merchant state. SPA re-fetches after every mutation.",
    endpoints: [
      { method: "GET", path: "/api/state", purpose: "Returns merchant + all related entities in one response" },
    ],
    models: ["ALL"],
    notes: [
      "Single GET returns: merchant, staff[], customers[], stampCards[], customerStampCards[] (with stamps), rewards[], bills[] (last 200), redemptions[] (last 200), referrals[], auditLogs[] (last 200), waMessages[] (last 100), subscriptions[], reviews[], birthdays[], vipTiers[], winBacks[], achievements[], supportTickets[], onboardingSteps[].",
      "Demo is single-tenant — picks first Merchant. Multi-tenant would filter by merchantId from auth context.",
      "All Promise.all'd for parallel DB queries. SQLite is single-writer but multi-reader, so reads parallelize fine.",
      "After any POST mutation, the frontend calls fetchState() to refresh. No optimistic UI in demo — server is source of truth.",
      "In production, replace with granular endpoints + TanStack Query for caching. Snapshot is fine for demo but won't scale past ~10K records.",
      "Achievement query uses where: { customer: { merchantId } } — nested relation filter. Prisma supports this.",
    ],
  },
]



