// CustomerPilot V6 — PRODUCTION POLICIES
// 12 production behavior policies addressing the second ChatGPT audit.
// Each policy: Scenario / Decision Matrix / Behavior / State Machine / Edge Cases / Audit Actions / Code Reference.
//
// IMPORTANT: No new product modules. These are behavioral clarifications +
// minimal enforcement code for policies that need it.

export interface PolicyChapter {
  id: string
  number: number
  title: string
  category: "Critical" | "High" | "Medium"
  tagline: string
  scenario: string
  decisionMatrix: { option: string; tradeoff: string; recommended: boolean }[]
  behavior: string[]
  stateMachine?: { states: string[]; transitions: { from: string; to: string; trigger: string }[] }
  edgeCases: string[]
  auditActions: string[]
  codeReference: string
}

export const PRODUCTION_POLICIES: PolicyChapter[] = [
  {
    id: "rule-change-migration",
    number: 1,
    title: "Rule Change Migration Policy",
    category: "Critical",
    tagline: "When owner changes stampsRequired (9 to 6) or reward cost (1 to 2 cards), what happens to existing cards?",
    scenario:
      "Month 6: Owner Ravi changes 'Cake Lover's Card' from 9 stamps to 6 stamps. Customer A has 5 stamps, Customer B has 6 stamps. Should B instantly get a reward? Should A's progress bar jump? Can Ravi preview before applying? Can he rollback?",
    decisionMatrix: [
      { option: "Apply to future cards only (new cards created after rule change)", tradeoff: "Safest. Existing customers keep old contract. But some customers may feel unfairly locked into a harder rule.", recommended: false },
      { option: "Apply to all active cards instantly (current V6 behavior)", tradeoff: "Simple. Customer B gets instant reward. But A may feel cheated (was 4 stamps away, now 1 away — but no instant reward).", recommended: false },
      { option: "Apply to all active cards + preview + 24h rollback window", tradeoff: "Best of both. Owner sees impact preview ('3 customers will instantly complete'). Can rollback within 24h if change was a mistake.", recommended: true },
      { option: "Apply from selected future date", tradeoff: "Useful for planned promotions ('From Diwali, only 6 stamps needed'). But adds complexity.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Apply to all active cards + preview + 24h rollback window'.",
      "Owner opens stamp card edit dialog, changes stampsRequired from 9 to 6.",
      "System shows impact preview BEFORE saving: 'X customers currently at 6+ stamps will instantly have completed cards. Y customers at 4-5 stamps are now 1-2 away.'",
      "Owner confirms. Rule applies immediately.",
      "Customers at 6+ stamps: CustomerStampCard.completed auto-set to true, WhatsApp 'reward_ready' queued.",
      "Customers at 4-5 stamps: stampsCollected unchanged, but progress bar visually jumps closer to goal (because denominator shrank).",
      "AuditLog: CARD_EDITED with oldStampsRequired, newStampsRequired, impactedCustomerCount.",
      "24-hour rollback window: Owner can click 'Undo rule change' on the card. System reverses — completed cards reset, stampsCollected recalculated against old threshold. WhatsApp 'apologies, rule change reversed' sent to impacted customers.",
      "After 24h: change becomes permanent. No rollback possible.",
    ],
    stateMachine: {
      states: ["draft_change", "previewed", "applied", "rolled_back", "permanent"],
      transitions: [
        { from: "draft_change", to: "previewed", trigger: "Owner clicks 'Preview impact'" },
        { from: "previewed", to: "applied", trigger: "Owner clicks 'Confirm and apply'" },
        { from: "applied", to: "rolled_back", trigger: "Owner clicks 'Undo' within 24h" },
        { from: "applied", to: "permanent", trigger: "24h elapse without rollback" },
      ],
    },
    edgeCases: [
      "Reward cost change (1 card to 2 cards): Grandfather existing completed cards for 30 days at old cost. New cards follow new cost. Prevents burning loyal customers.",
      "Stamp rule change (1 per $10 to 1 per $15): Only affects future bills. Past stamps not recalculated.",
      "Card deactivated (active=false): Existing in-progress cards stay active until redeemed or expired. No new cards created from this template.",
      "Rollback after customer already redeemed the instantly-completed card: Redemption stays. Owner absorbs the cost. AuditLog captures the sequence.",
    ],
    auditActions: ["CARD_EDITED", "CARD_RULE_CHANGE_PREVIEWED", "CARD_RULE_CHANGE_APPLIED", "CARD_RULE_CHANGE_ROLLED_BACK"],
    codeReference: "POST /api/cards with cardId triggers preview mode. New field CardRuleChangeLog stores old/new values + rollback deadline.",
  },
  {
    id: "vip-eligibility-policy",
    number: 2,
    title: "VIP Tier Eligibility Policy (Lifetime vs Rolling)",
    category: "Critical",
    tagline: "Bakery: lifetime Gold is fine. Salon/Gym/Restaurant: inactive Gold members for years is a problem. Merchant chooses.",
    scenario:
      "Sweet Crumb Bakery: Meera hits Gold (₹5,000 spend) and stays Gold forever — even if she stops visiting for 2 years. For a bakery this is OK (low marginal cost). But for a Salon where Gold = 30% off, an inactive Gold member is a revenue leak. The merchant needs to choose.",
    decisionMatrix: [
      { option: "Lifetime VIP (current V6 behavior) — tier never downgrades", tradeoff: "Simplest. Best for low-marginal-cost businesses (bakery, cafe). Worst for high-marginal-cost (salon, gym).", recommended: false },
      { option: "Rolling 12-month VIP — tier based on last 12 months spend only", tradeoff: "Fair for high-cost businesses. But harsh — a loyal 5-year customer loses Gold after one quiet year.", recommended: false },
      { option: "Rolling 24-month VIP — tier based on last 24 months spend", tradeoff: "Balanced. Gives customers a longer grace period. Slightly more complex.", recommended: false },
      { option: "Merchant setting: choose Lifetime / Rolling-12mo / Rolling-24mo per merchant", tradeoff: "Maximum flexibility. Merchant picks at signup based on business type. Default by business type.", recommended: true },
    ],
    behavior: [
      "DEFAULT POLICY: 'Merchant setting with business-type default'.",
      "On signup, merchant picks VIP eligibility mode. Default by business type:",
      "  - cafe, bakery, retail → Lifetime (low marginal cost)",
      "  - salon, gym, restaurant, spa → Rolling 12-month (high marginal cost)",
      "  - other → Rolling 24-month (balanced)",
      "Merchant can override default in Settings → VIP Configuration.",
      "Cron (weekly Monday 9 AM): for merchants with Rolling mode, recompute each customer's rolling-window spend.",
      "If rolling spend drops below tier threshold: customer is downgraded ONE tier (Platinum → Gold, Gold → Silver, Silver → none). Never jumps two tiers in one cycle.",
      "Downgrade is NOT instant — customer gets 30-day grace + WhatsApp: 'Your Gold status is at risk. Visit us by [date] to maintain it.'",
      "If customer visits during grace: status maintained for another 12 months.",
      "If grace expires: downgrade applied. Achievement badge stays (historical record) but active perks revoked.",
      "Upgrades remain instant (no grace).",
      "AuditLog: VIP_TIER_DOWNGRADED with oldTier, newTier, reason='rolling_window_expired'.",
    ],
    stateMachine: {
      states: ["stable", "at_risk", "grace_period", "downgraded"],
      transitions: [
        { from: "stable", to: "at_risk", trigger: "Rolling spend drops below threshold" },
        { from: "at_risk", to: "grace_period", trigger: "30-day grace starts (WhatsApp sent)" },
        { from: "grace_period", to: "stable", trigger: "Customer visits during grace" },
        { from: "grace_period", to: "downgraded", trigger: "Grace expires with no visit" },
        { from: "downgraded", to: "stable", trigger: "Customer re-qualifies via new spend (instant upgrade)" },
      ],
    },
    edgeCases: [
      "Merchant switches from Lifetime to Rolling mode: existing VIPs keep their tier for 12 months from switch date, then rolling logic applies.",
      "Merchant switches from Rolling to Lifetime: all current tiers frozen permanently.",
      "Customer in grace period redeems a reward: reward proceeds normally (perks still active during grace).",
      "Customer downgraded mid-redemption-flow: pending_redemptions proceed at old tier cost. New redemptions follow new tier.",
    ],
    auditActions: ["VIP_TIER_UPGRADED", "VIP_TIER_DOWNGRADED", "VIP_TIER_AT_RISK", "VIP_CONFIG_CHANGED"],
    codeReference: "Merchant.vipEligibilityMode field (lifetime|rolling_12mo|rolling_24mo). Cron: vip-recompute.ts. New field Customer.vipTierAtRiskUntil (nullable date).",
  },
  {
    id: "review-reward-lifecycle",
    number: 3,
    title: "Google Review Reward Lifecycle",
    category: "Critical",
    tagline: "Customer edits review, deletes it, gives 1-star, or submits duplicate from same Google account. Bonus stamps lifecycle.",
    scenario:
      "Meera submits a 5-star review, gets 2 bonus stamps. Next day she edits it to 3 stars (the cake was actually stale). Or she deletes it entirely. Or her roommate uses the same Google account to submit a 2nd review for the same bakery. What happens to her bonus stamps?",
    decisionMatrix: [
      { option: "Bonus stamps are permanent once awarded — never clawed back", tradeoff: "Simplest. But incentivizes review-spam (submit, get stamps, delete, repeat).", recommended: false },
      { option: "Claw back bonus stamps on any edit/delete/rating-drop", tradeoff: "Strict. But harsh on legitimate edits ('fixed a typo'). Customer feels punished.", recommended: false },
      { option: "Claw back only on DELETE or rating drop below 3 stars. Edits that keep rating >=4 keep bonus.", tradeoff: "Balanced. Protects against fraud without punishing honest refinements.", recommended: true },
      { option: "Time-decayed clawback: full clawback within 7 days, 50% within 30 days, 0% after 30 days", tradeoff: "Most fair. Accounts for review 'aging'. Complex to implement.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Claw back on DELETE or rating drop below 3 stars. Edits keeping rating >=4 keep bonus.'",
      "On review submission: bonus stamps awarded immediately. Customer gets WhatsApp thank-you.",
      "Webhook from Google (production): if review is EDITED and new rating >= 4 → no action. Bonus stays.",
      "If review is EDITED and new rating drops to 1-2 stars → claw back bonus stamps. Stamp rows deleted, CustomerStampCard.stampsCollected decremented. WhatsApp: 'Your review was updated. The bonus stamps have been reversed.'",
      "If review is DELETED → claw back bonus stamps (regardless of original rating). Same reversal flow.",
      "If review is FLAGGED as fake by Google → claw back + customer flagged for fraud review.",
      "DUPLICATE PREVENTION: one bonus per (customerId, platform) per 90 days. If customer submits a 2nd review within 90 days, no bonus awarded. WhatsApp: 'Thanks for another review! Bonus stamps are awarded once per 90 days.'",
      "Same Google account, different customer profiles: blocked at signup (phone uniqueness already enforced).",
      "Clawback is silent on Customer.lifetimeStamps (which is a historical metric) — only active card balance is reversed.",
      "AuditLog: REVIEW_BONUS_CLAWED_BACK with reason (deleted|rating_dropped|flagged_fake).",
    ],
    stateMachine: {
      states: ["submitted", "bonus_awarded", "edited", "deleted", "clawed_back", "flagged_fake"],
      transitions: [
        { from: "submitted", to: "bonus_awarded", trigger: "POST /api/reviews/submit" },
        { from: "bonus_awarded", to: "edited", trigger: "Google webhook: review edited" },
        { from: "edited", to: "clawed_back", trigger: "New rating < 3 stars → clawback" },
        { from: "bonus_awarded", to: "deleted", trigger: "Google webhook: review deleted" },
        { from: "deleted", to: "clawed_back", trigger: "Automatic clawback on delete" },
        { from: "bonus_awarded", to: "flagged_fake", trigger: "Google flags review as fake" },
        { from: "flagged_fake", to: "clawed_back", trigger: "Automatic clawback + fraud review" },
      ],
    },
    edgeCases: [
      "Customer claws back bonus, then re-submits a new review within 90 days: no new bonus (duplicate window).",
      "Clawback would make CustomerStampCard.stampsCollected negative: clamp to 0, log the discrepancy.",
      "Customer claws back bonus after redeeming the reward it helped complete: redemption stays. Owner absorbs cost. Same pattern as bill-refund-after-redemption.",
      "Google API outage: webhook delayed by 24h+ → clawback still proceeds when webhook arrives. AuditLog timestamp reflects actual clawback, not original edit.",
    ],
    auditActions: ["REVIEW_BONUS_AWARDED", "REVIEW_BONUS_CLAWED_BACK", "REVIEW_FLAGGED_FAKE", "REVIEW_DUPLICATE_BLOCKED"],
    codeReference: "Webhook endpoint: POST /api/reviews/webhook (TODO). Field Review.clawedBackAt (nullable). Field Review.bonusClawbackReason. Duplicate check: db.review.findFirst({ where: { customerId, platform, status: 'submitted', submittedAt: { gte: now - 90d } } }).",
  },
  {
    id: "birthday-correction",
    number: 4,
    title: "Birthday Correction Workflow",
    category: "Critical",
    tagline: "Birthday unknown / wrong / edited / duplicate. What happens to scheduled rewards and already-redeemed bonuses?",
    scenario:
      "Meera registers without birthday (cashier forgot to ask). She visits 3 months later and mentions 'my birthday was last week'. Or: cashier entered wrong birthday (12-03 instead of 12-30). Or: customer has 2 records with different birthdays (duplicate).",
    decisionMatrix: [
      { option: "Birthday is immutable once set", tradeoff: "Simplest. But punishes data-entry errors and customer honesty.", recommended: false },
      { option: "Birthday editable anytime, no questions asked", tradeoff: "Customer-flexible. But enables abuse (change birthday to 'today' for free reward).", recommended: false },
      { option: "Birthday editable with manager approval + 30-day cooldown per customer", tradeoff: "Balanced. Prevents abuse. Manager verifies via customer ID or verbal confirmation.", recommended: true },
      { option: "Birthday editable only within 7 days of original entry", tradeoff: "Strict. But what if customer mentions wrong birthday 2 months later?", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Birthday editable with manager approval + 30-day cooldown per customer'.",
      "BIRTHDAY UNKNOWN: Customer.birthday = null. No Birthday record exists. No automated reminders. Cashier can ask and add anytime (counts as first set, no cooldown).",
      "BIRTHDAY FIRST SET: Manager or cashier enters. No approval needed (it's the first time). Birthday record created. Next occurrence scheduled.",
      "BIRTHDAY EDIT (already set): Requires MANAGER role. Customer.birthdayLastEditedAt recorded. Cooldown: 30 days from last edit before another edit allowed.",
      "If edit attempted within cooldown: 'Birthday was last edited on X. Please wait until Y to edit again.' 409 error.",
      "EDIT AFTER BIRTHDAY WINDOW: If customer's birthday window already passed this year and they didn't redeem, manager can edit and the new birthday applies next year.",
      "EDIT DURING BIRTHDAY WINDOW: If customer already redeemed this year, edit blocked until next year ('Birthday reward already redeemed for this year').",
      "DUPLICATE BIRTHDAY (merge scenario): When merging 2 customer records with different birthdays, manager picks which birthday to keep. Other is discarded.",
      "WRONG BIRTHDAY (customer reports): Customer says 'you have my birthday wrong, it's actually X'. Manager verifies (verbal confirmation of month is usually enough). Edits birthday. Cooldown applies.",
      "AuditLog: BIRTHDAY_EDITED with oldBirthday, newBirthday, editedBy, reason.",
    ],
    stateMachine: {
      states: ["unknown", "set", "edit_requested", "edited", "cooldown"],
      transitions: [
        { from: "unknown", to: "set", trigger: "First birthday entry (any staff)" },
        { from: "set", to: "edit_requested", trigger: "Manager opens edit dialog" },
        { from: "edit_requested", to: "edited", trigger: "Manager confirms new birthday (cooldown check passes)" },
        { from: "edited", to: "cooldown", trigger: "30-day cooldown starts" },
        { from: "cooldown", to: "set", trigger: "30 days elapse" },
      ],
    },
    edgeCases: [
      "Customer has birthday Feb 29 (leap year): treated as Feb 28 in non-leap years. System handles automatically.",
      "Customer born in current month: 'birthday' interpreted as upcoming occurrence, not past. Reminder scheduled for next year if window already passed.",
      "Manager edits birthday to today's date (suspicious): system allows but flags for fraud review. AuditLog: BIRTHDAY_EDITED_SUSPICIOUS.",
      "Bulk import with birthday column: all birthdays set as 'first set' (no cooldown). But if same customer exists with birthday, import skips that field.",
    ],
    auditActions: ["BIRTHDAY_SET", "BIRTHDAY_EDITED", "BIRTHDAY_EDIT_BLOCKED_COOLDOWN", "BIRTHDAY_EDIT_SUSPICIOUS", "BIRTHDAY_MERGED"],
    codeReference: "Field Customer.birthdayLastEditedAt (nullable). Field Customer.birthdayEditCooldownUntil (nullable). Endpoint POST /api/birthdays extended with manager approval check.",
  },
  {
    id: "campaign-priority-engine",
    number: 5,
    title: "Campaign Priority Engine",
    category: "High",
    tagline: "Customer has birthday + win-back + festival + VIP upgrade same week. Don't send 4 WhatsApp messages. Priority queue.",
    scenario:
      "Kavya's birthday is next week. She's also at 45 days inactive (win-back day_45). Sweet Crumb is running a Diwali festival campaign. And she just crossed ₹10,000 spend (Platinum upgrade). Without priority, Kavya gets 4 WhatsApp messages in 5 days — annoying.",
    decisionMatrix: [
      { option: "Send all messages — customer can mute if annoyed", tradeoff: "Simple. But high unsub rate. WhatsApp provider may flag as spam.", recommended: false },
      { option: "One message per customer per day, no exceptions", tradeoff: "Strict. But important messages (birthday) may get delayed.", recommended: false },
      { option: "Priority engine: 1 message per customer per 48h, highest priority wins", tradeoff: "Balanced. Birthday always wins. Lower-priority messages suppressed or delayed.", recommended: true },
      { option: "Message bundle: combine into one digest message", tradeoff: "Elegant but complex to draft. 'Happy birthday + Diwali offer + you're now Platinum' reads weird.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Priority engine: 1 message per customer per 48h, highest priority wins'.",
      "Priority order (highest to lowest):",
      "  1. Birthday reward_ready (highest — time-sensitive, only 7-day window)",
      "  2. Birthday reminder_sent",
      "  3. Win-back day_60 / day_90 (manager/owner call tasks — these are phone calls, not WhatsApp, so no collision)",
      "  4. Win-back day_30 / day_45 (WhatsApp)",
      "  5. VIP tier upgrade notification",
      "  6. Festival / campaign broadcast",
      "  7. Review request (post-redemption)",
      "  8. Stamp earned (transactional — always sent, exempt from suppression)",
      "  9. Redemption confirm (transactional — always sent, exempt)",
      "TRANSACTIONAL EXEMPTION: stamp_earned, redemption_confirm, referral_bonus are transactional (triggered by customer action). Always sent immediately, never suppressed.",
      "MARKETING MESSAGES: birthday, win-back, VIP upgrade, festival, review_request are marketing. Subject to 48h suppression.",
      "WHEN COLLISION DETECTED: system checks WhatsAppMessage queue for customer in last 48h. If a marketing message exists:",
      "  - If new message has HIGHER priority → new message sent, old message's lower-priority content appended as P.S. (e.g. 'P.S. Also: Diwali double stamps this Friday!')",
      "  - If new message has LOWER priority → suppressed. AuditLog: MESSAGE_SUPPRESSED. Message stays in queue with status='suppressed'. Sent 48h later if still relevant.",
      "BUNDLING: if 2+ marketing messages collide within 6h, system bundles into one message: 'Hi Kavya! 🎂 Happy birthday week — free slice waiting. Also: you're now Platinum VIP (50% bonus stamps!). Also: Diwali double stamps Friday.'",
      "Dashboard widget: 'WhatsApp sent today' shows actual count vs. attempted count, with suppression ratio.",
    ],
    stateMachine: {
      states: ["queued", "priority_check", "sent", "suppressed", "bundled", "delayed_48h"],
      transitions: [
        { from: "queued", to: "priority_check", trigger: "Background worker picks up" },
        { from: "priority_check", to: "sent", trigger: "Transactional OR no collision OR highest priority" },
        { from: "priority_check", to: "suppressed", trigger: "Lower priority than existing recent message" },
        { from: "priority_check", to: "bundled", trigger: "2+ marketing messages collide within 6h" },
        { from: "suppressed", to: "delayed_48h", trigger: "48h elapsed, recheck relevance" },
        { from: "delayed_48h", to: "sent", trigger: "Still relevant (e.g. festival ongoing)" },
        { from: "delayed_48h", to: "expired", trigger: "No longer relevant (e.g. birthday passed)" },
      ],
    },
    edgeCases: [
      "Birthday on Diwali day: birthday message wins (priority 1). Diwali festival P.S. appended. One message sent.",
      "Customer in win-back day_45 receives a stamp_earned (they returned!): stamp_earned is transactional, sent immediately. Win-back auto-marked 'recovered' — no day_45 message sent.",
      "Festival broadcast to 180 customers: each customer checked individually. Some may be suppressed if they got a higher-priority message in last 48h.",
      "Manager manually triggers a 'we miss you' message to a customer who just got a birthday message: suppressed, manager sees toast 'Suppressed — customer got birthday message 2h ago. Try again in 46h.'",
    ],
    auditActions: ["MESSAGE_SENT", "MESSAGE_SUPPRESSED", "MESSAGE_BUNDLED", "MESSAGE_DELAYED", "MESSAGE_EXPIRED"],
    codeReference: "New lib: src/lib/campaign-priority-engine.ts. Function: shouldSendMessage(customerId, template) → { send: boolean, suppress: boolean, bundleWith?: string[], delayUntil?: Date }. New table: CampaignDeliveryLog (customerId, template, priority, sentAt|suppressedAt).",
  },
  {
    id: "reward-stock-out",
    number: 6,
    title: "Reward Stock-Out Behavior",
    category: "High",
    tagline: "Reward stock = 0. Customer wants to redeem. Alternative? Waitlist? Replace? Don't lose the moment.",
    scenario:
      "Kavya wants to redeem 'Free Brownie' but stock = 0 (Sunita forgot to bake today). Kavya has a completed card. She's at the counter. Don't send her away empty-handed.",
    decisionMatrix: [
      { option: "Block redemption — 'Sorry, out of stock. Try again tomorrow.'", tradeoff: "Simplest. But customer loses trust in the program. May not return.", recommended: false },
      { option: "Auto-offer cheapest in-stock alternative", tradeoff: "Fast. But may offer a low-value reward customer doesn't want.", recommended: false },
      { option: "Cashier picks from in-stock alternatives + optional waitlist for original", tradeoff: "Flexible. Customer chooses. Waitlist captures restock intent.", recommended: true },
      { option: "Auto-issue raincheck voucher (digital, 30-day validity)", tradeoff: "Clean. But adds voucher management complexity.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Cashier picks from in-stock alternatives + optional waitlist for original'.",
      "Customer at counter with completed card. Cashier taps 'Redeem' on 'Free Brownie'.",
      "POS shows modal: '⚠ Free Brownie is out of stock. Options:'",
      "  1. Pick alternative (list of in-stock rewards at same or lower cost): 'Free Cupcake (in stock)', 'Free Pastry (in stock)'",
      "  2. Waitlist for Free Brownie (card stays completed, customer gets WhatsApp when restocked)",
      "  3. Save card for later (no action, customer keeps completed card)",
      "If cashier picks ALTERNATIVE: standard redemption flow on the alternative reward. Original card consumed.",
      "If cashier picks WAITLIST: RewardWaitlist row created (customerId, rewardId, createdAt). Customer's completed card stays completed (not consumed). When reward restocked (stock > 0), cron checks waitlist FIFO:",
      "  - First customer in waitlist gets WhatsApp: 'Good news! Free Brownie is back in stock. Your completed card is ready — visit within 7 days.'",
      "  - 7-day window to redeem. If not redeemed, next customer in waitlist gets the chance.",
      "  - If waitlist > restock quantity: only top N customers notified. Rest stay in queue.",
      "If cashier picks SAVE CARD: no action. Customer keeps completed card. Can redeem later when stock returns.",
      "Dashboard alert: 'Reward restock needed' shows when any reward stock <= 5 OR waitlist length > 3.",
      "AuditLog: REDEMPTION_OUT_OF_STOCK (attempt), REDEMPTION_ALTERNATIVE_OFFERED, REWARD_WAITLISTED, REWARD_RESTOCKED, WAITLIST_CUSTOMER_NOTIFIED.",
    ],
    stateMachine: {
      states: ["in_stock", "low_stock", "out_of_stock", "waitlisted", "restocked", "notified", "redeemed_via_waitlist", "expired"],
      transitions: [
        { from: "in_stock", to: "low_stock", trigger: "stock <= 5" },
        { from: "low_stock", to: "out_of_stock", trigger: "stock = 0" },
        { from: "out_of_stock", to: "waitlisted", trigger: "Customer added to waitlist" },
        { from: "waitlisted", to: "restocked", trigger: "Manager updates stock > 0" },
        { from: "restocked", to: "notified", trigger: "Cron notifies top N waitlist customers" },
        { from: "notified", to: "redeemed_via_waitlist", trigger: "Customer redeems within 7 days" },
        { from: "notified", to: "expired", trigger: "7 days elapse without redemption" },
      ],
    },
    edgeCases: [
      "All rewards out of stock simultaneously: POS shows 'All rewards temporarily out of stock. Save card for later?'. No alternative to offer.",
      "Customer on waitlist redeems a different reward instead: waitlist entry auto-removed. Next customer moves up.",
      "Reward permanently discontinued (active=false): waitlist cleared. All waitlisted customers get WhatsApp: 'Sorry, Free Brownie has been discontinued. Your completed card is still valid for other rewards.'",
      "Customer at waitlist position #5, only 3 restocked: customer not notified. Stays in queue for next restock.",
    ],
    auditActions: ["REDEMPTION_OUT_OF_STOCK", "REDEMPTION_ALTERNATIVE_OFFERED", "REWARD_WAITLISTED", "REWARD_RESTOCKED", "WAITLIST_CUSTOMER_NOTIFIED", "WAITLIST_ENTRY_EXPIRED"],
    codeReference: "New table: RewardWaitlist (id, merchantId, customerId, rewardId, createdAt, notifiedAt, expiresAt, status). Cron: waitlist-flush.ts runs hourly. Endpoint: POST /api/rewards/waitlist.",
  },
  {
    id: "owner-manual-override",
    number: 7,
    title: "Owner Manual Override Workflow",
    category: "High",
    tagline: "Owner wants to manually give a customer a reward or bonus stamps. No bill, no redemption flow. Just 'give'.",
    scenario:
      "Kavya's birthday cake was slightly burnt. Owner Ravi wants to apologize — give her 3 bonus stamps + a free pastry, no strings. Or: Meera referred 5 friends, Ravi wants to give her a surprise free cake. No bill, no redemption. Just owner discretion.",
    decisionMatrix: [
      { option: "No override path — owner must use standard flows (create a ₹0 bill, then redeem)", tradeoff: "Audit-clean. But feels hacky. ₹0 bills pollute revenue reports.", recommended: false },
      { option: "Owner override: give stamps + give reward, no questions asked", tradeoff: "Fast. But no abuse protection. Cashier could misuse if they have owner PIN.", recommended: false },
      { option: "Owner override with mandatory reason + audit log + monthly cap (5 overrides/month)", tradeoff: "Balanced. Owner has discretion but pattern is auditable.", recommended: true },
      { option: "Owner override requires co-approval from manager", tradeoff: "Strictest. But slow for time-sensitive apologies (customer at counter).", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Owner override with mandatory reason + audit log + monthly cap (5 overrides/month)'.",
      "Owner opens customer profile, clicks 'Manual Override'.",
      "Modal: 'Override type: [Bonus stamps] [Free reward] [Both]. Reason (required, min 10 chars): _____. Amount/Reward: _____.'",
      "Owner submits. System checks monthly cap: db.auditLog.count({ where: { action: 'OWNER_OVERRIDE', staffId: owner.id, createdAt: { gte: startOfMonth } } }).",
      "If cap exceeded: 'You've used 5 overrides this month. Contact support to increase the cap.' 403.",
      "If within cap: override applied.",
      "  - Bonus stamps: Stamp rows created with source='manual_override'. CustomerStampCard.stampsCollected incremented.",
      "  - Free reward: Redemption row created with status='completed', approvedById=owner.id, notes='Manual override: <reason>'. Reward.stock NOT decremented (it's a gift, not inventory consumption).",
      "WhatsApp to customer (optional, owner toggles): 'Hi {name}! {merchant} has gifted you {reward/bonus}. Reason: {reason}.'",
      "Dashboard widget: 'Overrides this month: 3/5'. Owner can see own override history.",
      "AuditLog: OWNER_OVERRIDE with type, amount, reason, customerId. Reviewed monthly by support team for abuse patterns.",
      "Manager CANNOT override — only Owner role. Prevents cashier+manager collusion.",
    ],
    stateMachine: {
      states: ["initiated", "cap_checked", "applied", "cap_exceeded", "reviewed"],
      transitions: [
        { from: "initiated", to: "cap_checked", trigger: "Owner submits override form" },
        { from: "cap_checked", to: "applied", trigger: "Monthly cap not exceeded" },
        { from: "cap_checked", to: "cap_exceeded", trigger: "5 overrides already used this month" },
        { from: "applied", to: "reviewed", trigger: "Monthly support review" },
      ],
    },
    edgeCases: [
      "Owner overrides bonus stamps that complete a card: card.completed = true, reward_ready WhatsApp sent (normal flow continues).",
      "Owner overrides a free reward that requires manager approval: approval bypassed (owner is highest authority). Redemption status='completed' immediately.",
      "Override used for fraud (owner giving free rewards to friends): pattern detected in monthly review. Support can suspend owner account.",
      "Monthly cap reset: 1st of each month, 00:00 merchant timezone. Unused cap doesn't roll over.",
    ],
    auditActions: ["OWNER_OVERRIDE", "OWNER_OVERRIDE_CAP_EXCEEDED", "OWNER_OVERRIDE_REVIEWED"],
    codeReference: "Endpoint: POST /api/owner-override. Body: { staffId, customerId, type: 'stamps'|'reward'|'both', amount?, rewardId?, reason, notifyCustomer? }. Cap configurable in Merchant.overrideCapPerMonth (default 5).",
  },
  {
    id: "customer-merge",
    number: 8,
    title: "Duplicate Customer Merge Workflow",
    category: "High",
    tagline: "Same customer registered twice (Meera Iyer + Meera Iyer (Bakry)). Merge without losing history.",
    scenario:
      "Cashier search shows 2 records: 'Meera Iyer' (5 bills, 7 stamps) and 'Meera Iyer (Bakry)' (2 bills, 4 stamps). Same phone. Different name spellings. Need to merge into one canonical record.",
    decisionMatrix: [
      { option: "Hard delete duplicate — keep the older record", tradeoff: "Data loss. 2 bills and 4 stamps gone.", recommended: false },
      { option: "Merge: copy all bills/stamps/redemptions to canonical, soft-delete duplicate", tradeoff: "Clean. But merge direction (which is canonical?) matters.", recommended: true },
      { option: "Merge: keep newer record as canonical (more accurate data)", tradeoff: "Risk: newer record may have less history. Older record may have achievements.", recommended: false },
      { option: "Auto-merge on phone match (no human review)", tradeoff: "Fast. But risky — 2 different people with same phone (family landline) would be wrongly merged.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Manual merge by manager — pick canonical, migrate all data, soft-delete duplicate'.",
      "Manager opens Customers tab, sees duplicate flag (system auto-detects same phone).",
      "Clicks 'Merge' on one of the records.",
      "Modal: 'Select canonical record (the one to keep):' with radio buttons for each duplicate.",
      "Manager picks canonical (usually the one with more history, or the one with correct name spelling).",
      "Preview: 'Record A (canonical) will absorb: 2 bills, 4 stamps, 1 redemption, 1 achievement from Record B. Record B will be soft-deleted.'",
      "Manager confirms. Transaction:",
      "  - All Bill rows where customerId = B → updated to customerId = A",
      "  - All Stamp rows where customerId = B → updated to customerId = A",
      "  - All CustomerStampCard rows where customerId = B → updated to customerId = A (if A doesn't have an active card for same template, otherwise stamps merged into A's card)",
      "  - All Redemption rows where customerId = B → updated to customerId = A",
      "  - All Review rows where customerId = B → updated to customerId = A",
      "  - All Referral rows where referrerId = B → updated to referrerId = A",
      "  - All Achievement rows where customerId = B → updated to customerId = A (duplicates de-duped by type)",
      "  - All WhatsAppMessage rows where customerId = B → updated to customerId = A",
      "  - All WinBackEscalation rows where customerId = B → updated to customerId = A",
      "  - Customer B: status='merged', mergedIntoId=A.id, soft-deleted (excluded from default queries)",
      "  - Customer A: lifetimeStamps += B.lifetimeStamps, lifetimeSpend += B.lifetimeSpend, lifetimeRedemptions += B.lifetimeRedemptions",
      "  - Birthday conflict (A and B have different birthdays): manager picks which to keep during merge dialog.",
      "  - VIP tier conflict: A keeps the higher tier (never downgrade on merge).",
      "AuditLog: CUSTOMER_MERGED with canonicalId, duplicateId, migratedCounts.",
      "Merge is IRREVERSIBLE after 7 days. Within 7 days, owner can 'unmerge' (restores B as separate record, reverses data migration).",
    ],
    stateMachine: {
      states: ["duplicate_detected", "merge_initiated", "canonical_selected", "merged", "unmerge_window", "permanent"],
      transitions: [
        { from: "duplicate_detected", to: "merge_initiated", trigger: "Manager clicks Merge" },
        { from: "merge_initiated", to: "canonical_selected", trigger: "Manager picks canonical record" },
        { from: "canonical_selected", to: "merged", trigger: "Manager confirms preview" },
        { from: "merged", to: "unmerge_window", trigger: "7-day unmerge window starts" },
        { from: "unmerge_window", to: "permanent", trigger: "7 days elapse" },
        { from: "unmerge_window", to: "duplicate_detected", trigger: "Owner clicks Unmerge (reverses migration)" },
      ],
    },
    edgeCases: [
      "3+ duplicates (triple merge): manager merges pairwise. A absorbs B, then A absorbs C.",
      "Duplicate has active referral pending: referral migrates to canonical. If canonical is the referrer (self-referral loop), referral denied + flagged.",
      "Duplicate has pending redemption (status=pending_approval): migrates to canonical. Manager approves from canonical's profile.",
      "Family members with same phone (legitimate): merge is OPTIONAL. Manager can mark 'not a duplicate' to suppress the flag.",
      "Customer was blocked in one record: canonical inherits blocked status. Owner must manually unblock if needed.",
    ],
    auditActions: ["CUSTOMER_MERGE_INITIATED", "CUSTOMER_MERGED", "CUSTOMER_UNMERGED", "DUPLICATE_FLAG_DISMISSED"],
    codeReference: "Endpoint: POST /api/customers/merge { staffId, canonicalId, duplicateId, keepBirthday: 'canonical'|'duplicate' }. Field Customer.mergedIntoId (nullable). Field Customer.mergedAt. Cron: cleanup merged records after 30 days (hard delete).",
  },
  {
    id: "merchant-transfer",
    number: 9,
    title: "Merchant Ownership Transfer",
    category: "High",
    tagline: "Bakery sold. New owner. Staff remain. Subscription remains. Data ownership transfer flow.",
    scenario:
      "Ravi sells Sweet Crumb Bakery to Anita on Month 8. Anita wants: keep all customer data, keep staff (Priya, Sunita), keep subscription (5 months remaining), but she becomes the new Owner. Ravi should lose access.",
    decisionMatrix: [
      { option: "New owner creates fresh account, old owner manually exports/reimports data", tradeoff: "Data loss risk. Subscription lost. Customer history fragmented.", recommended: false },
      { option: "Ownership transfer: old owner initiates, new owner accepts, all data stays", tradeoff: "Clean. Subscription, data, staff all preserved. Access transferred atomically.", recommended: true },
      { option: "Support-mediated transfer: both owners email support, support manually transfers", tradeoff: "Safest but slow (2-3 business days). Bad UX for time-sensitive sales.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Self-service ownership transfer with 7-day pending window'.",
      "Old owner (Ravi) opens Settings → Ownership → 'Transfer Ownership'.",
      "Form: 'New owner email + new owner name + confirmation checkbox (I understand I will lose access).' + reason.",
      "System creates MerchantTransferRequest { merchantId, oldOwnerId: Ravi.id, newOwnerEmail, newOwnerName, status: 'pending', expiresAt: now + 7d }.",
      "Email + WhatsApp to new owner (Anita): 'You've been invited to take ownership of Sweet Crumb Bakery. Accept at [link]. Link expires in 7 days.'",
      "Anita clicks link, creates account (or logs in if existing). Sees transfer preview:",
      "  - Merchant: Sweet Crumb Bakery",
      "  - Customers: 180 (all data preserved)",
      "  - Staff: 2 (Priya, Sunita — will remain)",
      "  - Subscription: 5 months remaining (₹4,500 value)",
      "  - Outstanding: 1 pending redemption, 2 pending referrals",
      "Anita clicks 'Accept Transfer'.",
      "Atomic transaction:",
      "  - New Staff row created: Anita, role=OWNER",
      "  - Old owner Staff row (Ravi): status='revoked' (can no longer login)",
      "  - Merchant.primaryOwnerId updated to Anita.id",
      "  - Subscription: no change (continues under merchant)",
      "  - All other Staff (Priya, Sunita): no change",
      "  - All Customer/Bill/Stamp/etc. data: no change (tied to merchantId, not ownerId)",
      "  - AuditLog: MERCHANT_OWNERSHIP_TRANSFERRED",
      "Ravi gets email: 'Ownership of Sweet Crumb Bakery has been transferred to Anita. You no longer have access.'",
      "7-day pending window: if Anita doesn't accept, request expires. Ravi retains ownership. Can re-initiate.",
      "ROLLBACK: within 24h of transfer, Ravi can click 'Cancel transfer' (Anita hasn't made changes yet). After 24h: irreversible.",
      "LEGAL COMPLIANCE: transfer creates a digital record (MerchantTransferLog) that can be exported as PDF for legal purposes ('As of [date], ownership transferred from Ravi to Anita. All customer data consent transferred per DPDP Act.').",
    ],
    stateMachine: {
      states: ["initiated", "pending_acceptance", "accepted", "completed", "expired", "cancelled", "rolled_back"],
      transitions: [
        { from: "initiated", to: "pending_acceptance", trigger: "Old owner submits transfer form" },
        { from: "pending_acceptance", to: "accepted", trigger: "New owner clicks Accept" },
        { from: "accepted", to: "completed", trigger: "Atomic transfer transaction succeeds" },
        { from: "pending_acceptance", to: "expired", trigger: "7 days elapse without acceptance" },
        { from: "pending_acceptance", to: "cancelled", trigger: "Old owner cancels before acceptance" },
        { from: "completed", to: "rolled_back", trigger: "Old owner cancels within 24h" },
        { from: "rolled_back", to: "initiated", trigger: "Old owner can re-initiate" },
      ],
    },
    edgeCases: [
      "New owner already has a CustomerPilot merchant account: blocked. 'Anita already owns another merchant account. Please use a different email or contact support for account consolidation.'",
      "Subscription payment failed during transfer: transfer proceeds (subscription status carries over). New owner must resolve payment.",
      "Old owner has pending support tickets: tickets remain open, assigned to merchant (new owner sees them).",
      "Old owner tries to login after transfer: 'Your access to Sweet Crumb Bakery has been revoked. Contact the current owner if you believe this is an error.'",
      "Disputed transfer (Ravi claims he didn't initiate): support can reverse if AuditLog shows suspicious IP/timing. 30-day dispute window.",
    ],
    auditActions: ["MERCHANT_TRANSFER_INITIATED", "MERCHANT_TRANSFER_ACCEPTED", "MERCHANT_OWNERSHIP_TRANSFERRED", "MERCHANT_TRANSFER_EXPIRED", "MERCHANT_TRANSFER_CANCELLED", "MERCHANT_TRANSFER_ROLLED_BACK", "MERCHANT_TRANSFER_DISPUTED"],
    codeReference: "New table: MerchantTransferLog (id, merchantId, oldOwnerId, newOwnerId, initiatedAt, acceptedAt, completedAt, status, reason, legalAttestationText). Endpoint: POST /api/merchant/transfer, POST /api/merchant/transfer/accept, POST /api/merchant/transfer/cancel.",
  },
  {
    id: "fraud-detection",
    number: 10,
    title: "Fraud Detection for Fake Bills",
    category: "Medium",
    tagline: "Cashier creates 5 fake bills for same customer in 10 minutes. Extra stamps. Detection rules.",
    scenario:
      "Cashier Priya wants to give her friend Meera extra stamps. She creates 5 fake bills of ₹50 each in 10 minutes (system awards 1 stamp per bill = 5 stamps). Or: cashier enters ₹0.01 bill to award a stamp without real revenue. Or: same customer billed 20 times in one day.",
    decisionMatrix: [
      { option: "No fraud detection — trust the cashier", tradeoff: "Simple. But enables stamp inflation. Owner may not notice for months.", recommended: false },
      { option: "Hard rules: block any bill < ₹10, block > 10 bills per customer per day", tradeoff: "Strict. But legitimate edge cases (₹5 coffee sample, festival rush 15 bills/day) get blocked.", recommended: false },
      { option: "Soft rules: flag suspicious patterns, alert manager, don't block", tradeoff: "Balanced. Owner/manager reviews flags. False positives don't block legitimate sales.", recommended: true },
      { option: "ML-based anomaly detection", tradeoff: "Most accurate. But requires training data, model maintenance, explainability. Overkill for V6.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Soft rules — flag suspicious patterns, alert manager, don't block'.",
      "Detection rules (run synchronously on every POST /api/bills):",
      "  RULE 1 — Low-value bill: amount < ₹10 → flag severity=low. Reason: 'Bill amount below ₹10 threshold.'",
      "  RULE 2 — Rapid repeat: same customerId + same amount within 5 minutes → flag severity=high. Reason: 'Same customer billed same amount within 5 minutes.'",
      "  RULE 3 — High frequency: same customerId > 8 bills in 24h → flag severity=medium. Reason: 'Customer billed 8+ times in 24h.'",
      "  RULE 4 — After-hours: bill created between 11 PM and 5 AM (merchant timezone) → flag severity=low. Reason: 'Bill created outside business hours.'",
      "  RULE 5 — Cashier self-deal: customerId matches cashier's own phone (cashier billing themselves) → flag severity=high. Reason: 'Cashier billing own account.'",
      "  RULE 6 — Stamp spike: customer's lifetimeStamps increased by >10 in 24h → flag severity=medium. Reason: 'Unusual stamp accumulation rate.'",
      "On flag creation: FraudAlert row created (merchantId, billId, ruleId, severity, status='open'). Bill STILL proceeds (soft rule). Stamps awarded normally.",
      "Dashboard widget (manager+ owner): 'Fraud alerts: 3 open'. Clicking shows alert list with rule, severity, bill details, cashier name.",
      "Manager reviews each alert: 'Mark as legitimate' (closes alert, notes reason) or 'Investigate' (escalates to owner, freezes stamps pending review).",
      "Owner can 'Reverse stamps' on confirmed fraud: stamps deleted, card reset, customer notified if appropriate.",
      "Pattern detection: if same cashier triggers >5 fraud alerts in 30 days, auto-escalate to owner with recommendation to review cashier access.",
      "AuditLog: FRAUD_ALERT_CREATED, FRAUD_ALERT_REVIEWED, FRAUD_ALERT_ESCALATED, FRAUD_STAMPS_REVERSED.",
    ],
    stateMachine: {
      states: ["open", "reviewing", "legitimate", "investigating", "confirmed_fraud", "stamps_reversed", "false_positive"],
      transitions: [
        { from: "open", to: "reviewing", trigger: "Manager opens alert" },
        { from: "reviewing", to: "legitimate", trigger: "Manager marks as legitimate" },
        { from: "reviewing", to: "investigating", trigger: "Manager escalates to owner" },
        { from: "investigating", to: "confirmed_fraud", trigger: "Owner confirms fraud" },
        { from: "investigating", to: "false_positive", trigger: "Owner marks as false positive" },
        { from: "confirmed_fraud", to: "stamps_reversed", trigger: "Owner reverses stamps" },
      ],
    },
    edgeCases: [
      "Festival rush: 15 bills/day for one customer (bulk order). Rule 3 fires. Manager marks legitimate. Pattern doesn't auto-escalate.",
      "Cashier gives self a stamp (legitimate — they bought a coffee): Rule 5 fires. Manager marks legitimate.",
      "Multiple cashiers colluding: pattern detected across staffIds. Owner alert: 'Pattern: 3 cashiers all billing same customer 5+ times. Possible collusion.'",
      "Customer legitimately visits 10 times in a day (rare but possible — office party ordering): Rule 3 fires. Manager marks legitimate.",
      "Fraud confirmed but customer already redeemed the fraudulently-earned reward: same pattern as refund-after-redemption. Owner absorbs cost. AuditLog captures sequence.",
    ],
    auditActions: ["FRAUD_ALERT_CREATED", "FRAUD_ALERT_REVIEWED", "FRAUD_ALERT_ESCALATED", "FRAUD_STAMPS_REVERSED", "FRAUD_PATTERN_DETECTED", "FRAUD_ALERT_FALSE_POSITIVE"],
    codeReference: "New table: FraudAlert (id, merchantId, billId, ruleId, severity, status, reviewedById, reviewedAt, notes). New lib: src/lib/fraud-detection.ts. Function: checkBillForFraud(bill) → FraudAlert[]. Called inside POST /api/bills after bill creation.",
  },
  {
    id: "ai-explanation-layer",
    number: 11,
    title: "AI Explanation Layer for Dashboard Insights",
    category: "Medium",
    tagline: "Dashboard says 'Repeat Rate ↓ 12%'. Merchant asks 'why?'. AI explanation layer answers.",
    scenario:
      "Ravi opens dashboard. Sees: 'Repeat Rate dropped 12% this month.' He panics. Why? Is it the new competitor? Bad cake quality? Or just seasonality? Without explanation, the number is noise.",
    decisionMatrix: [
      { option: "Raw numbers only — merchant interprets themselves", tradeoff: "Current state. Numbers without context. Merchant may misdiagnose.", recommended: false },
      { option: "Static tooltips — 'Repeat Rate = customers who visited 2+ times this month'", tradeoff: "Helps definition. But doesn't explain the trend.", recommended: false },
      { option: "AI explanation layer — for each KPI, AI generates 'Why this changed' + 'Recommended action'", tradeoff: "Most useful. But requires LLM integration. Demo uses template-based explanations.", recommended: true },
      { option: "Manual weekly report — support team emails insights", tradeoff: "High-quality but slow. Doesn't scale.", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'AI explanation layer with template-based explanations (demo) → LLM-powered (production)'.",
      "For each KPI on the dashboard (revenue, repeat rate, churn rate, redemption rate, reputation score, etc.):",
      "  - Show the number + trend arrow (up/down/flat vs last period)",
      "  - Show 'Why?' expandable section with AI explanation",
      "Explanation structure: 'Repeat Rate ↓ 12% because: (1) 8 customers moved to dormant status this month (vs 3 last month), (2) Birthday campaign reached fewer customers (3 vs 7 last month), (3) No festival campaign this month vs Diwali last month.'",
      "Recommended action: 'Re-engage dormant customers via win-back day_30 messages. Schedule a campaign next week.'",
      "Demo mode: explanations are template-based (rule engine that compares this month vs last month metrics).",
      "Production mode: swap template for LLM call (z-ai-web-dev-sdk chat completion with metric context).",
      "Explanations are generated on-demand (not pre-computed). Cached for 1 hour per merchant.",
      "Merchant can give feedback: '👍 Helpful' / '👎 Not helpful' on each explanation. Improves future explanations.",
      "Privacy: explanations only use merchant's own data. No cross-merchant benchmarking in V6.",
      "AuditLog: AI_INSIGHT_GENERATED with kpiName, explanation summary.",
    ],
    stateMachine: {
      states: ["metric_changed", "explanation_requested", "explanation_generated", "feedback_received"],
      transitions: [
        { from: "metric_changed", to: "explanation_requested", trigger: "Merchant expands 'Why?' section" },
        { from: "explanation_requested", to: "explanation_generated", trigger: "Template engine or LLM returns explanation" },
        { from: "explanation_generated", to: "feedback_received", trigger: "Merchant clicks 👍 or 👎" },
      ],
    },
    edgeCases: [
      "Metric is flat (no change): explanation = 'No significant change. Business as usual.'",
      "Metric is new (no last-period data): explanation = 'Insufficient historical data. Will be available next month.'",
      "Multiple factors: AI lists top 3 contributors by impact. Doesn't overwhelm with 10 reasons.",
      "LLM unavailable (production): fallback to template-based explanation. Silent degradation.",
      "Contradictory metrics (revenue up but repeat rate down): AI acknowledges the tension. 'Revenue ↑ 8% (driven by new customers) but Repeat Rate ↓ 12% (existing customers not returning). Focus on retention.'",
    ],
    auditActions: ["AI_INSIGHT_GENERATED", "AI_INSIGHT_FEEDBACK"],
    codeReference: "New lib: src/lib/insights-engine.ts. Function: explainMetric(metricName, currentValue, previousValue, context) → { summary, contributors: string[], recommendedAction }. Production: replace with z-ai-web-dev-sdk chat completion. Endpoint: POST /api/insights/explain.",
  },
  {
    id: "daily-summary-timing",
    number: 12,
    title: "Daily Summary Scheduling for Different Business Hours",
    category: "Medium",
    tagline: "Merchant closes shop at 11 PM. Daily summary at 6 PM misses 5 hours of revenue. Timezone-aware closing logic.",
    scenario:
      "Sweet Crumb Bakery closes at 9 PM. But some bakeries (wedding cake specialists) take orders until 11 PM. Restaurants open until 1 AM. A 6 PM daily summary is useless for them — it misses the dinner rush. Daily summary must respect merchant's business hours + timezone.",
    decisionMatrix: [
      { option: "Fixed 6 PM daily summary for all merchants", tradeoff: "Simple. But useless for late-closing businesses.", recommended: false },
      { option: "Fixed 11 PM daily summary (after most businesses close)", tradeoff: "Better. But midnight snack shops close at 3 AM.", recommended: false },
      { option: "Merchant configures business hours + timezone. Summary sent 1 hour after closing.", tradeoff: "Most accurate. Merchant gets summary when day is truly done.", recommended: true },
      { option: "Merchant configures summary time manually (any time of day)", tradeoff: "Flexible. But merchant may pick wrong time (e.g. 9 AM, missing previous day's evening).", recommended: false },
    ],
    behavior: [
      "DEFAULT POLICY: 'Merchant configures business hours + timezone. Summary sent 1 hour after closing.'",
      "On signup, merchant picks:",
      "  - Timezone (default: Asia/Kolkata for Indian merchants, auto-detected from browser)",
      "  - Business hours: open time + close time (e.g. 9 AM - 9 PM)",
      "  - Closed days (e.g. Sundays closed — no summary sent on Sundays)",
      "Default business hours by type:",
      "  - cafe: 8 AM - 8 PM",
      "  - bakery: 9 AM - 9 PM",
      "  - salon: 10 AM - 7 PM",
      "  - restaurant: 11 AM - 11 PM",
      "  - retail: 10 AM - 10 PM",
      "DAILY SUMMARY CRON: runs every 15 minutes. For each merchant:",
      "  - Compute current time in merchant's timezone",
      "  - If current time == closing time + 1 hour (within 15-min window) AND today is not a closed day:",
      "    - Generate daily summary WhatsApp",
      "  - Else: skip",
      "Summary content (for the day just ended, in merchant timezone):",
      "  - Bills count, revenue, stamps awarded",
      "  - New customers, top customer",
      "  - Pending approvals (carried to next day)",
      "  - Tomorrow's preview: birthdays, scheduled campaigns",
      "EDGE CASE — past-midnight closing (restaurant closes at 1 AM):",
      "  - Summary sent at 2 AM. Counts as 'yesterday's' summary (the day that started at 11 AM and ended at 1 AM).",
      "  - Bills from 12 AM - 1 AM counted in previous day's summary, not today's.",
      "EDGE CASE — 24-hour business (no closing time):",
      "  - Summary sent at 3 AM (quietest hour for most businesses).",
      "  - Day defined as 3 AM to 3 AM.",
      "EDGE CASE — multi-shift business (open 6 AM - 2 AM with shift change at 10 PM):",
      "  - Single daily summary at 3 AM (after close).",
      "  - Owner can request 'shift-wise summary' (premium feature, not in V6).",
      "TODAY'S BRIEFING (morning): sent at opening time. Content: today's birthdays, pending approvals from yesterday, low-stock alerts.",
      "Merchant can override: 'Send summary at fixed X PM regardless of closing time' (Settings → Schedule).",
      "AuditLog: DAILY_SUMMARY_SENT with sentAt, timezone, coversPeriod (start, end).",
    ],
    stateMachine: {
      states: ["before_close", "closing_window", "summary_window", "summary_sent", "closed_day"],
      transitions: [
        { from: "before_close", to: "closing_window", trigger: "Current time in closing hour" },
        { from: "closing_window", to: "summary_window", trigger: "Closing time reached" },
        { from: "summary_window", to: "summary_sent", trigger: "1 hour after closing (cron fires)" },
        { from: "summary_sent", to: "before_close", trigger: "Next day's opening time" },
        { from: "before_close", to: "closed_day", trigger: "Today is a closed day" },
        { from: "closed_day", to: "before_close", trigger: "Next day (open day)" },
      ],
    },
    edgeCases: [
      "Daylight saving: India doesn't observe DST, but merchants in other countries might. Timezone-aware cron handles automatically via IANA timezone database.",
      "Merchant changes business hours mid-month: cron picks up new hours immediately. No historical summary regeneration.",
      "Merchant closes early unexpectedly (sick day): no summary sent that day (closing time not reached). Next day's summary covers 2 days. Or merchant manually triggers summary from Settings.",
      "Internet outage at summary time: cron retries every 15 min for 2 hours. If still failing, summary skipped, next day's summary covers 2 days.",
      "Merchant in different timezone than their customers: summary always in merchant's timezone. Customer-facing WhatsApp timestamps in customer's timezone (best-effort, may differ for cross-timezone customers).",
    ],
    auditActions: ["DAILY_SUMMARY_SENT", "DAILY_SUMMARY_SKIPPED_CLOSED_DAY", "DAILY_SUMMARY_FAILED", "MORNING_BRIEFING_SENT", "BUSINESS_HOURS_CHANGED"],
    codeReference: "Fields on Merchant: timezone (default 'Asia/Kolkata'), openTime, closeTime, closedDays (JSON array like ['sunday']), summaryTimeOverride (nullable). Cron: daily-summary.ts runs every 15 min, computes per-merchant timing. Lib: src/lib/business-hours.ts with functions nowInMerchantTz(merchant), isWithinBusinessHours(merchant), nextSummaryTime(merchant).",
  },
]
